version: '3'
services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq
    ports:
      - "5672:5672"
      - "15672:15672"
    
  token-management:
    image: token-management
    container_name: token-management

  account-management:
    image: account-management
    container_name: account-management

  payment:
    image: payment
    container_name: payment
