version: '3'
services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    
  token-management:
    image: token-management
    container_name: token-management

  account-management:
    image: account-management
    container_name: account-management

  payment:
    image: payment
    container_name: payment

  reporting:
    image: reporting
    container_name: reporting

  customer-api:
    image: customer-api
    container_name: customer-api
    ports:
      - "8080:8080"

  merchant-api:
    image: merchant-api
    container_name: merchant-api
    ports:
      - "8081:8080"

  manager-api:
    image: manager-api
    container_name: manager-api
    ports:
      - "8082:8080"
